version: '3.8'

services:
  # IEN Research Intelligence Platform - Production with Traefik
  ien-platform:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ien-research-platform
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3000
      - HOSTNAME=0.0.0.0
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "node", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
